application: twixip
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /(.*)/sync
  script: main.py
  login: admin

- url: /_add_user
  script: main.py
  login: admin